import streamlit as st
import requests
import google.generativeai as genai
from datetime import datetime
from fpdf import FPDF

# --- API CONFIGURATION ---
GEMINI_API_KEY = "AIzaSyDPbHNSw_1Qz6_XsMKaoyT8oTNAohznFmE"
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash')

# Page configuration
st.set_page_config(page_title="Visionary AI | Minimal", page_icon="🌑", layout="wide")

# Initialize Session States
if "ai_plan" not in st.session_state: st.session_state.ai_plan = ""
if "chat_history" not in st.session_state: st.session_state.chat_history = []
if "tasks" not in st.session_state: st.session_state.tasks = []

# --- CSS: CYBER-MINIMALIST & SMALLER FONT SIZES ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=IBM+Plex+Mono:wght@400;600&display=swap');

    html, body, [class*="st-"] {
        font-family: 'Outfit', sans-serif;
        color: #cfd2d6;
    }

    h1 {
        font-family: 'Outfit', sans-serif !important;
        font-weight: 800 !important;
        font-size: 1.8rem !important;
        letter-spacing: -0.5px;
        margin-bottom: 0px !important;
    }
    
    h2, h3 {
        font-family: 'Outfit', sans-serif !important;
        font-weight: 600 !important;
        font-size: 1rem !important;
        text-transform: uppercase;
    }

    .stApp { background: #0a0b10; }
    
    .custom-card {
        background: rgba(255, 255, 255, 0.01);
        padding: 25px;
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.05);
        font-family: 'Outfit', sans-serif;
        line-height: 1.5;
        font-size: 0.9rem;
    }
    
    .stButton>button {
        border-radius: 6px;
        background: transparent;
        color: #e2c275 !important;
        font-weight: 600;
        font-size: 0.75rem;
        text-transform: uppercase;
        border: 1px solid #e2c275;
        letter-spacing: 1px;
    }
    
    .stButton>button:hover {
        background: #e2c275;
        color: #000000 !important;
    }
    
    [data-testid="stMetricValue"] {
        font-family: 'IBM Plex Mono', monospace !important;
        color: #e2c275 !important;
        font-size: 1.2rem !important;
        font-weight: 600 !important;
    }
    
    [data-testid="stMetricLabel"] {
        font-size: 0.7rem !important;
        text-transform: uppercase;
        opacity: 0.5;
    }

    section[data-testid="stSidebar"] { background-color: #08090d !important; }
    </style>
    """, unsafe_allow_html=True)

# --- PDF FORMATTING ENGINE ---
def create_pdf(name, content):
    pdf = FPDF()
    pdf.add_page()
    
    # Title Header
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 15, f"VISIONARY ROADMAP: {name.upper()}", ln=True, align='C')
    pdf.set_draw_color(226, 194, 117)
    pdf.line(20, 25, 190, 25)
    pdf.ln(10)
    
    # Content Formatting
    pdf.set_font("Arial", size=11)
    pdf.set_text_color(50, 50, 50)
    
    # Clean up text for FPDF encoding
    clean_text = content.encode('latin-1', 'ignore').decode('latin-1')
    
    # Use multi_cell for automatic wrapping and proper alignment
    pdf.multi_cell(0, 8, txt=clean_text, align='L')
    
    # Footer in PDF
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by aisardzul | Built for the Visionaries | 2025-2030", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- WEATHER ENGINE ---
def get_weather(state):
    coords = {"Selangor": (3.07, 101.51), "W.P. Kuala Lumpur": (3.13, 101.68), "Johor": (1.48, 103.74)}
    lat, lon = coords.get(state, (3.13, 101.68))
    try:
        data = requests.get(f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=True").json()
        return f"{data['current_weather']['temperature']}°C"
    except: return "N/A"

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("### ⚙️ SYSTEM CONFIG")
    name = st.text_input("Full Name", placeholder="Aisar Zul")
    age = st.number_input("Age", min_value=1, value=25)
    career = st.text_input("Current Industry", placeholder="AI Engineering")
    location = st.selectbox("Base Location", ["Selangor", "W.P. Kuala Lumpur", "Johor", "Pulau Pinang", "Sabah", "Sarawak"])
    vibe = st.selectbox("AI Persona", ["The Strategist", "The Realist", "The Mentor"])
    dream = st.text_area("2030 Vision")
    gen_btn = st.button("EXECUTE GENERATION")

# --- HEADER ---
temp = get_weather(location)
c_t, c_w = st.columns([3, 1])
with c_t:
    st.markdown(f"<h1>HELLO, <span style='color:#e2c275'>{name.upper() if name else 'VISIONARY'}</span>.</h1>", unsafe_allow_html=True)
    st.markdown("<p style='font-size:0.75rem; opacity:0.4; letter-spacing: 2px;'>SYSTEM STATUS: ONLINE | ARCHITECTING 2030</p>", unsafe_allow_html=True)

with c_w:
    st.markdown(f"""
    <div style="text-align: right; background: rgba(255,255,255,0.01); padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.05);">
        <span style="color: #444; font-family: 'IBM Plex Mono'; font-size: 0.9rem;">{datetime.now().strftime('%d.%m.%Y').upper()}</span><br>
        <span style="color: #e2c275; font-family: 'IBM Plex Mono'; font-size: 0.9rem; font-weight: 600;">{temp}</span>
    </div>
    """, unsafe_allow_html=True)

st.write("")
m1, m2, m3, m4 = st.columns(4)
m1.metric("STATUS", "IDLE" if not st.session_state.ai_plan else "ACTIVE")
m2.metric("TARGET", "2030")
m3.metric("STYLE", vibe.split()[-1].upper())
m4.metric("TASKS", len([t for t in st.session_state.tasks if not t['done']]))
st.divider()

# --- TABS ---
t1, t2, t3 = st.tabs(["STRATEGIC ROADMAP", "AI CONSULTANT", "MILESTONES"])

with t1:
    if gen_btn:
        if not name or not dream: st.warning("Incomplete profile data.")
        else:
            with st.spinner("Processing trajectory..."):
                prompt = f"Role: {vibe}. Generate a detailed, professional 5-year roadmap for {name}, a {age}-year-old in {career}, based in {location}. Their ultimate vision is: {dream}. Use bullet points and clear year-by-year headers."
                st.session_state.ai_plan = model.generate_content(prompt).text

    if st.session_state.ai_plan:
        st.markdown(f'<div class="custom-card">{st.session_state.ai_plan}</div>', unsafe_allow_html=True)
        st.write("")
        
        # DOWNLOAD PDF BUTTON
        pdf_data = create_pdf(name if name else "Visionary", st.session_state.ai_plan)
        st.download_button(
            label="📄 DOWNLOAD FORMATTED PDF",
            data=pdf_data,
            file_name=f"{name}_Roadmap_2030.pdf",
            mime="application/pdf"
        )
    else:
        st.info("Input configuration and execute generation.")

with t2:
    if st.session_state.ai_plan:
        for chat in st.session_state.chat_history:
            with st.chat_message(chat["role"]): st.markdown(f"<span style='font-size:0.85rem'>{chat['content']}</span>", unsafe_allow_html=True)
        if user_in := st.chat_input("Query the system..."):
            st.session_state.chat_history.append({"role": "user", "content": user_in})
            res = model.generate_content(f"Plan: {st.session_state.ai_plan}. Question: {user_in}").text
            st.session_state.chat_history.append({"role": "assistant", "content": res})
            st.rerun()
    else: st.warning("System offline. Generate roadmap first.")

with t3:
    ci, cb = st.columns([0.8, 0.2])
    ti = ci.text_input("New Protocol:", placeholder="e.g. Master Cloud Architecture")
    if cb.button("COMMIT"):
        if ti:
            st.session_state.tasks.append({"task": ti, "done": False})
            st.rerun()
    st.write("")
    for i, t in enumerate(st.session_state.tasks):
        cc, ct, cd = st.columns([0.05, 0.85, 0.1])
        st.session_state.tasks[i]["done"] = cc.checkbox("", value=t["done"], key=f"c_{i}")
        label = f"<span style='opacity:0.3; font-size:0.85rem'>~~{t['task']}~~</span>" if t['done'] else f"<span style='font-size:0.85rem'>{t['task']}</span>"
        ct.markdown(label, unsafe_allow_html=True)
        if cd.button("DEL", key=f"d_{i}"):
            st.session_state.tasks.pop(i)
            st.rerun()

# --- FOOTER ---
st.markdown(f"""
    <div style="text-align: center; color: #222; font-family: 'IBM Plex Mono'; font-size: 0.6rem; margin-top: 100px; letter-spacing: 5px;">
        AISARDZUL | PROJECT_VISIONARY | 2025-2030
    </div>
""", unsafe_allow_html=True)